
# Use ck-launch-session in runlevel 3,
# to start and attach a ConsoleKit session to the X session:
mkdir -p $PKG/etc/X11/xinit
cat $CWD/xinit/xinitrc.plasma \
  | sed -e "s/@LIBDIRSUFFIX@/$LIBDIRSUFFIX/g" \
  > $PKG/etc/X11/xinit/xinitrc.plasma
chmod 0755 $PKG/etc/X11/xinit/xinitrc.plasma

# Add a "fail-safe" version of KDE Plasma desktop session:
mkdir -p $PKG/usr/share/xsessions
cat $CWD/xsession/plasma-safe.desktop \
  | sed -e "s,@PREFIX@,/usr,g" \
  >  $PKG/usr/share/xsessions/plasma-safe.desktop

# What is "plugins/plugins"?
if [ -d $PKG/usr/lib${LIBDIRSUFFIX}/qt5/plugins/plugins ]; then
  mv $PKG/usr/lib${LIBDIRSUFFIX}/qt5/plugins/{plugins,}/phonon_platform
  rmdir $PKG/usr/lib${LIBDIRSUFFIX}/qt5/plugins/plugins
fi

# Move the polkit dbus configuration files to the proper place:
mkdir -p $PKG/etc
mv $PKG/etc/kde/dbus-1 $PKG/etc/

# For shadow, this file needs to be setuid root just like the KDE4 version:
chmod +s $PKG/usr/lib$LIBDIRSUFFIX/kcheckpass

